name: PlatformIO CI

on: [push]

jobs:
  update-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clone the documentation repository.
        uses: actions/checkout@v3
        with:
          repository: Nexonous/Documentation
          path: Documentation
          submodules: true
      
      - name: Creating the new issue on the Documentation repository.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}

        run: |
          export PEREGRINE_VERSION=$(git log -1 --format=%cd --date=format:v%Y-%m-%d)

          git config --global user.name ${{ github.actor }} 
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          cd Documentation

          git checkout -b update/$PEREGRINE_VERSION
          git submodule add https://git@github.com/Nexonous/Peregrine content/Peregrine/$PEREGRINE_VERSION
          git add .
          git commit -m "Updated Peregrine to new version: $PEREGRINE_VERSION"
          git push -u origin update/$PEREGRINE_VERSION
