name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Build Debug
        run: pio run --environment esp32-debug

      - name: Build Production Test
        run: pio run --environment esp32-production-test

      - name: Build Release
        run: pio run --environment esp32-release

  update-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Creating the new issue on the Documentation repository.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}

        run: |
          export PEREGRINE_VERSION=$(git log -1 --format=%cd --date=format:v%Y-%m-%d)

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://$USERNAME:$REPO_KEY@github.com/Nexonous/Documentation
          cd Documentation

          git checkout -b update/$PEREGRINE_VERSION
          git submodule add https://github.com/Nexonous/Peregrine content/Peregrine/$PEREGRINE_VERSION
          git add .
          git commit -m "Updated Peregrine to new version: $PEREGRINE_VERSION"
          git push -u origin update/$PEREGRINE_VERSION
