name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Build Debug
        run: pio run --environment esp32-debug

      - name: Build Production Test
        run: pio run --environment esp32-production-test

      - name: Build Release
        run: pio run --environment esp32-release

  update-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clone the documentation repository.
        run: gh repo clone https://github.com/Nexonous/Documentation
        
      - name: Copy the documentation folder into the documentation content.
        run: |
          cd Documentation
          export PEREGRINE_VERSION=$(git log -1 --format=%cd --date=format:v%Y.%m.%d)
          gh issue create --title "Test issue for Peregrine" --body "A new version is up!" --assignee @me --label "enhancement"



